// =========================================================================
// GEMIOS APP REGISTRY & STORE CATALOG - v36.3 (THE REMOVAL UPDATE)
// =========================================================================

window.GemiRegistry = {
    // === SYSTEM CORE APPS ===
    'sys_term': { icon: '⌨️', title: 'Bash Terminal', width: 500, html: (pid) => `<div id="t-out-${pid}" style="flex-grow:1; background:#0a0a0a; color:#38ef7d; padding:10px; font-family:monospace; overflow-y:auto; border-radius:6px;">GemiOS Shell Active. Type 'help' or 'gpm install [app]'</div><div style="display:flex; background:#111; padding:8px; border-radius:6px; margin-top:5px;"><span id="t-path-${pid}" style="color:#0078d7; margin-right:8px; font-weight:bold;">C:/Users/${GemiOS.user}></span><input type="text" id="t-in-${pid}" style="flex-grow:1; background:transparent; color:#38ef7d; border:none; outline:none; font-family:monospace;" onkeydown="GemiOS.handleTerm(event, ${pid}, this)"></div>`, onLaunch: (pid) => { GemiOS.termStates[pid] = 'C:/Users/' + GemiOS.user; setTimeout(()=>document.getElementById('t-in-'+pid).focus(),100); } },
    'sys_drive': { icon: '🗂️', title: 'Explorer 2.0', width: 520, html: (pid) => `<div class="sys-card" style="display:flex; gap:10px; align-items:center; background:rgba(0,120,215,0.2);"><button onclick="GemiOS.navDrive(${pid}, 'UP')" class="btn-sec" style="width:auto; margin:0; padding:5px 10px;">⬆️ Up</button><input type="text" id="d-path-${pid}" value="C:/" disabled style="flex-grow:1; background:transparent; color:inherit; border:none; font-weight:bold; font-size:14px; outline:none;"></div><div id="d-list-${pid}" style="flex-grow:1; min-height:200px; overflow-y:auto; display:grid; grid-template-columns:repeat(auto-fill, minmax(80px, 1fr)); gap:10px;"></div><div style="margin-top:10px; padding:5px; background:rgba(0,0,0,0.3); border-radius:4px;"><div style="display:flex; justify-content:space-between; font-size:11px; margin-bottom:3px;"><span id="d-bar-text-${pid}">Calculating NVRAM...</span><span>10MB MAX</span></div><div style="height:6px; background:#222; border-radius:3px; overflow:hidden;"><div id="d-bar-${pid}" style="height:100%; background:var(--accent); width:0%; transition: width 0.3s ease;"></div></div></div>`, onLaunch: (pid) => { GemiOS.driveStates[pid] = 'C:/Users/' + GemiOS.user; GemiOS.renderDrive(pid); GemiOS.driveItvs = GemiOS.driveItvs || {}; GemiOS.driveItvs[pid] = setInterval(() => { let u = GemiOS.VFS.getUsage(); let pct = Math.max((u.used / u.max) * 100, 0.5); let bar = document.getElementById(`d-bar-${pid}`); let txt = document.getElementById(`d-bar-text-${pid}`); if(bar) { bar.style.width = Math.min(pct, 100) + '%'; bar.style.background = pct > 90 ? '#ff4d4d' : 'var(--accent)'; } if(txt) txt.innerText = `${(u.used/1024).toFixed(2)} KB Used`; }, 500); }, onKill: (pid) => { if(GemiOS.driveItvs && GemiOS.driveItvs[pid]) clearInterval(GemiOS.driveItvs[pid]); } },
    'sys_set': { icon: '⚙️', title: 'System Settings', width: 420, html: () => `<div class="sys-card"><b style="font-size:14px;">Wallpaper Engine</b><br><input type="text" id="wp-in" style="width:100%; margin:8px 0; padding:8px; border-radius:4px; border:none; outline:none; background:rgba(255,255,255,0.9); color:black;" placeholder="Image URL..."><button onclick="localStorage.setItem('GemiOS_Wall', document.getElementById('wp-in').value); location.reload();" class="btn-primary">Apply Wallpaper</button></div><div class="sys-card"><b style="font-size:14px;">Accent Color</b><br><div style="display:flex; gap:10px; margin-top:10px;"><div onclick="localStorage.setItem('GemiOS_Accent', '#0078d7'); location.reload();" style="width:30px; height:30px; border-radius:50%; background:#0078d7; cursor:pointer;"></div><div onclick="localStorage.setItem('GemiOS_Accent', '#ff00cc'); location.reload();" style="width:30px; height:30px; border-radius:50%; background:#ff00cc; cursor:pointer;"></div><div onclick="localStorage.setItem('GemiOS_Accent', '#38ef7d'); location.reload();" style="width:30px; height:30px; border-radius:50%; background:#38ef7d; cursor:pointer;"></div><div onclick="localStorage.setItem('GemiOS_Accent', '#ff4d4d'); location.reload();" style="width:30px; height:30px; border-radius:50%; background:#ff4d4d; cursor:pointer;"></div><div onclick="localStorage.setItem('GemiOS_Accent', '#ffb400'); location.reload();" style="width:30px; height:30px; border-radius:50%; background:#ffb400; cursor:pointer;"></div></div></div><div class="sys-card" style="border-left:4px solid var(--accent);"><b style="font-size:14px;">GemiSync (Export OS)</b><br><button onclick="GemiOS.exportNVRAM()" class="btn-primary" style="margin-top:5px;">Export .gemos Backup</button></div><button onclick="alert('Please restart and use F2 BIOS menu for Secure Erase.')" class="btn-danger">Format System (Moved to BIOS)</button>` },
    'sys_update': { icon: '☁️', title: 'Cloud Updater', width: 380, html: () => `<div class="sys-card" style="text-align:center; flex-grow:1;"><div style="font-size:40px;">☁️</div><h3 style="margin:5px 0;">GitHub Updater</h3><p style="font-size:13px; opacity:0.8;">Registry: <b id="kern-ver">v36.3.0-REMOVAL</b></p><div id="upd-stat" style="font-size:12px; min-height:15px;"></div><button id="upd-btn" onclick="GemiOS.triggerOTA(this)" class="btn-primary" style="margin-top:10px;">Check for Updates</button></div>` },
    'sys_log': { icon: '📋', title: 'Chronicles', width: 500, html: () => `<div style="flex-grow:1; overflow-y: auto; padding-right: 5px;"><div class="sys-card" style="border-left:4px solid #38ef7d;"><b>v36.3.0 (The Removal Update)</b> - Purged Arcade games (GemiCraft, Pong, Snake, etc.) to optimize registry memory. Added GemiFlow and GemiCrypt.</div><div class="sys-card"><b>v36.2.0 (The Perfection Patch)</b> - Re-written GemiCraft logic loop.</div><div class="sys-card"><b>v36.0.0 (The Expansion)</b> - Modular Registry updated natively.</div><div class="sys-card"><b>v33.1.0 (Infinity Kernel)</b> - Unified architecture.</div></div>` },
    'sys_store': { icon: '🛍️', title: 'GemiStore Mega', width: 700, html: (pid) => `<div class="sys-card" style="display:flex; justify-content:space-between; align-items:center; background:linear-gradient(135deg, var(--accent), #000); border:none;"><div style="font-size:24px; font-weight:bold;">GemiStore</div><div style="font-size:40px;">🛍️</div></div><div id="store-list-${pid}" style="flex-grow:1; overflow-y:auto; display:grid; grid-template-columns:1fr 1fr; gap:10px; padding-right:5px;"></div>`, onLaunch: (pid) => { GemiOS.renderStore(pid); } },
    'sys_disk': { icon: '💽', title: 'GemiDisk', width: 400, html: (pid) => `<div class="sys-card" style="text-align:center;"><div style="font-size:40px;">💽</div><h3 style="margin:5px 0;">NVRAM Status</h3><p style="font-size:12px; opacity:0.8;">Strict Quota Enforced</p><div style="width:100%; height:20px; background:rgba(0,0,0,0.5); border-radius:10px; overflow:hidden; border:1px solid rgba(255,255,255,0.2); margin:15px 0;"><div id="disk-fill-${pid}" style="width:0%; height:100%; background:var(--accent); transition:width 0.5s ease;"></div></div><b id="disk-text-${pid}">Calculating...</b></div>`, onLaunch: (pid) => { GemiOS.diskItvs = GemiOS.diskItvs || {}; GemiOS.diskItvs[pid] = setInterval(() => { let u = GemiOS.VFS.getUsage(); let pct = Math.max((u.used / u.max) * 100, 0.2); let elF = document.getElementById(`disk-fill-${pid}`); let elT = document.getElementById(`disk-text-${pid}`); if(elF) { elF.style.width = Math.min(pct, 100) + '%'; elF.style.background = pct > 90 ? '#ff4d4d' : 'var(--accent)'; } if(elT) elT.innerText = `${(u.used/1024).toFixed(2)} KB / 10.00 MB`; }, 500); }, onKill: (pid) => { if(GemiOS.diskItvs && GemiOS.diskItvs[pid]) clearInterval(GemiOS.diskItvs[pid]); } },
    'sys_task': { icon: '📊', title: 'System Monitor', width: 450, html: (pid) => `<div style="display:flex; gap:10px;"><div class="sys-card" style="flex:1; border-left: 4px solid #38ef7d;"><b>CPU</b><canvas id="cpu-cvs-${pid}" width="180" height="80"></canvas></div><div class="sys-card" style="flex:1; border-left: 4px solid #4db8ff;"><b>RAM</b><canvas id="ram-cvs-${pid}" width="180" height="80"></canvas></div></div><div class="sys-card" style="border-left: 4px solid #ff4d4d; margin-top:10px;"><b>PIDs</b></div><div id="tm-list-${pid}" style="flex-grow:1; overflow-y:auto;"></div>`, onLaunch: (pid) => { let cpuH = [], ramH = []; GemiOS.tmItvs = GemiOS.tmItvs || {}; GemiOS.tmItvs[pid] = setInterval(() => { let h = ''; let pCount = 0; for(let p in GemiOS.PM.processes) { pCount++; h += `<div style="padding:8px; background:rgba(255,255,255,0.1); margin-bottom:5px; border-radius:4px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:13px;">${GemiOS.PM.processes[p].title} [${p}]</span><button onclick="GemiOS.PM.kill(${p})" class="btn-danger" style="padding:4px 8px; width:auto; font-size:11px;">Kill</button></div>`; } let el = document.getElementById(`tm-list-${pid}`); if(el) el.innerHTML = h; let cCvs = document.getElementById(`cpu-cvs-${pid}`); let rCvs = document.getElementById(`ram-cvs-${pid}`); if(cCvs && rCvs) { let cCtx = cCvs.getContext('2d'); let rCtx = rCvs.getContext('2d'); cpuH.push(Math.random() * 20 + (pCount*5)); if(cpuH.length>30) cpuH.shift(); ramH.push(pCount * 12 + (Math.random()*5)); if(ramH.length>30) ramH.shift(); cCtx.clearRect(0,0,180,80); rCtx.clearRect(0,0,180,80); cCtx.strokeStyle = '#38ef7d'; cCtx.lineWidth = 2; cCtx.beginPath(); cpuH.forEach((v,i) => i===0 ? cCtx.moveTo(i*6, 80-v) : cCtx.lineTo(i*6, 80-v)); cCtx.stroke(); rCtx.strokeStyle = '#4db8ff'; rCtx.lineWidth = 2; rCtx.beginPath(); ramH.forEach((v,i) => i===0 ? rCtx.moveTo(i*6, 80-v) : rCtx.lineTo(i*6, 80-v)); rCtx.stroke(); } }, 1000); }, onKill: (pid) => clearInterval(GemiOS.tmItvs[pid]) },
    
    // === NEW V36.3 PRODUCTIVITY APPS ===
    'GemiFlow.app': { 
        desc: 'Kanban board for project tracking.', icon: '📋', title: 'GemiFlow Tasks', width: 700, 
        html: (pid) => `
            <div style="display:flex; gap:15px; flex-grow:1; background:#111; padding:15px; border-radius:8px;">
                <div class="sys-card" style="flex:1; display:flex; flex-direction:column; background:rgba(255,77,77,0.1); border:1px solid rgba(255,77,77,0.3);">
                    <b style="color:#ff4d4d; border-bottom:1px solid rgba(255,77,77,0.3); padding-bottom:5px; margin-bottom:10px;">TO DO</b>
                    <div id="flow-todo-${pid}" style="flex-grow:1; overflow-y:auto; display:flex; flex-direction:column; gap:5px;"></div>
                    <button onclick="let t=prompt('New Task:'); if(t) { document.getElementById('flow-todo-${pid}').innerHTML += '<div style=\\'background:#222; padding:8px; border-radius:4px; font-size:12px;\\'>'+t+'</div>'; }" class="btn-sec" style="margin-top:10px; padding:5px;">+ Add Task</button>
                </div>
                <div class="sys-card" style="flex:1; display:flex; flex-direction:column; background:rgba(255,180,0,0.1); border:1px solid rgba(255,180,0,0.3);">
                    <b style="color:#ffb400; border-bottom:1px solid rgba(255,180,0,0.3); padding-bottom:5px; margin-bottom:10px;">DOING</b>
                    <div id="flow-doing-${pid}" style="flex-grow:1; overflow-y:auto; display:flex; flex-direction:column; gap:5px;"></div>
                    <button onclick="let t=prompt('Task:'); if(t) { document.getElementById('flow-doing-${pid}').innerHTML += '<div style=\\'background:#222; padding:8px; border-radius:4px; font-size:12px;\\'>'+t+'</div>'; }" class="btn-sec" style="margin-top:10px; padding:5px;">+ Add Task</button>
                </div>
                <div class="sys-card" style="flex:1; display:flex; flex-direction:column; background:rgba(56,239,125,0.1); border:1px solid rgba(56,239,125,0.3);">
                    <b style="color:#38ef7d; border-bottom:1px solid rgba(56,239,125,0.3); padding-bottom:5px; margin-bottom:10px;">DONE</b>
                    <div id="flow-done-${pid}" style="flex-grow:1; overflow-y:auto; display:flex; flex-direction:column; gap:5px;"></div>
                    <button onclick="let t=prompt('Task:'); if(t) { document.getElementById('flow-done-${pid}').innerHTML += '<div style=\\'background:#222; padding:8px; border-radius:4px; font-size:12px;\\'>'+t+'</div>'; }" class="btn-sec" style="margin-top:10px; padding:5px;">+ Add Task</button>
                </div>
            </div>` 
    },
    'GemiCrypt.app': { 
        desc: 'Simulated live market ticker.', icon: '📈', title: 'GemiCrypt Dashboard', width: 500, 
        html: (pid) => `
            <div style="background:#0a0a0a; padding:15px; border-radius:6px; flex-grow:1; display:flex; flex-direction:column;">
                <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:15px;">
                    <div style="font-family:monospace; font-size:24px; color:#38ef7d; font-weight:bold;">GEMI: $<span id="crypt-prc-${pid}">100.00</span></div>
                    <div style="font-size:12px; color:#888;">LIVE MARKET DATA</div>
                </div>
                <canvas id="crypt-cvs-${pid}" style="flex-grow:1; width:100%; border:1px solid #222; border-radius:4px; background:#050505;"></canvas>
            </div>`, 
        onLaunch: (pid) => { 
            setTimeout(() => { 
                let cvs = document.getElementById(`crypt-cvs-${pid}`); if(!cvs) return; 
                let ctx = cvs.getContext('2d'); 
                let price = 100.00; let hist = Array(50).fill(price); 
                GemiOS.cryptItvs = GemiOS.cryptItvs || {}; 
                GemiOS.cryptItvs[pid] = setInterval(() => { 
                    if(!document.getElementById(`crypt-cvs-${pid}`)) return clearInterval(GemiOS.cryptItvs[pid]); 
                    cvs.width = cvs.offsetWidth; cvs.height = cvs.offsetHeight; 
                    
                    // Random Walk Math
                    let change = (Math.random() - 0.48) * 4; 
                    price = Math.max(10, price + change); 
                    hist.push(price); if(hist.length > 50) hist.shift(); 
                    
                    let prcEl = document.getElementById(`crypt-prc-${pid}`);
                    prcEl.innerText = price.toFixed(2);
                    prcEl.style.color = change >= 0 ? '#38ef7d' : '#ff4d4d';
                    
                    ctx.clearRect(0,0,cvs.width,cvs.height); 
                    
                    // Grid
                    ctx.strokeStyle = '#222'; ctx.lineWidth = 1;
                    for(let i=0; i<5; i++) { ctx.beginPath(); ctx.moveTo(0, i*(cvs.height/4)); ctx.lineTo(cvs.width, i*(cvs.height/4)); ctx.stroke(); }
                    
                    // Chart
                    ctx.strokeStyle = change >= 0 ? '#38ef7d' : '#ff4d4d'; 
                    ctx.lineWidth = 2; 
                    ctx.beginPath(); 
                    let minP = Math.min(...hist) - 10; let maxP = Math.max(...hist) + 10;
                    let range = maxP - minP;
                    
                    hist.forEach((p,i) => { 
                        let x = (i/49)*cvs.width; 
                        let y = cvs.height - ((p - minP)/range)*cvs.height; 
                        if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y); 
                    }); 
                    ctx.stroke(); 
                }, 1000); 
            }, 100); 
        }, 
        onKill: (pid) => { if(GemiOS.cryptItvs && GemiOS.cryptItvs[pid]) clearInterval(GemiOS.cryptItvs[pid]); } 
    },

    // === EXISTING PROFESSIONAL APPS ===
    'GemiBrot.app': { desc: 'Mandelbrot Fractal render engine.', icon: '🌌', title: 'GemiBrot Explorer', width: 500, html: (pid) => `<div style="background:#000; flex-grow:1; display:flex; flex-direction:column; border-radius:6px; overflow:hidden;"><canvas id="brot-cvs-${pid}" style="width:100%; height:300px; background:black; cursor:crosshair;"></canvas><div style="padding:10px; background:#111; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:12px; color:#aaa;">Click to Zoom</span><button onclick="GemiOS.Registry['GemiBrot.app'].render(${pid}, -2.0, 0.5, -1.2, 1.2)" class="btn-primary" style="width:auto; margin:0;">Reset Math</button></div></div>`, onLaunch: (pid) => { setTimeout(() => { GemiOS.Registry['GemiBrot.app'].render(pid, -2.0, 0.5, -1.2, 1.2); let cvs = document.getElementById(`brot-cvs-${pid}`); cvs.onclick = (e) => { let rect = cvs.getBoundingClientRect(); let x = e.clientX - rect.left; let y = e.clientY - rect.top; let state = cvs.dataset; let w = parseFloat(state.xMax) - parseFloat(state.xMin); let h = parseFloat(state.yMax) - parseFloat(state.yMin); let nx = parseFloat(state.xMin) + (x / cvs.width) * w; let ny = parseFloat(state.yMin) + (y / cvs.height) * h; GemiOS.Registry['GemiBrot.app'].render(pid, nx - w/4, nx + w/4, ny - h/4, ny + h/4); }; }, 200); }, render: (pid, xMin, xMax, yMin, yMax) => { let cvs = document.getElementById(`brot-cvs-${pid}`); if(!cvs) return; cvs.width = cvs.offsetWidth; cvs.height = 300; cvs.dataset.xMin = xMin; cvs.dataset.xMax = xMax; cvs.dataset.yMin = yMin; cvs.dataset.yMax = yMax; let ctx = cvs.getContext('2d'); let imgData = ctx.createImageData(cvs.width, cvs.height); let data = imgData.data; let maxIter = 50; for(let px=0; px<cvs.width; px++) { for(let py=0; py<cvs.height; py++) { let x0 = xMin + (px / cvs.width) * (xMax - xMin); let y0 = yMin + (py / cvs.height) * (yMax - yMin); let x = 0, y = 0, iter = 0; while(x*x + y*y <= 4 && iter < maxIter) { let xtemp = x*x - y*y + x0; y = 2*x*y + y0; x = xtemp; iter++; } let idx = (py * cvs.width + px) * 4; let color = iter === maxIter ? 0 : (iter * 255 / maxIter); data[idx] = color; data[idx+1] = color * 0.5; data[idx+2] = color * 0.8; data[idx+3] = 255; } } ctx.putImageData(imgData, 0, 0); } },
    'GemiMark.app': { desc: 'Live Markdown HTML Editor.', icon: '📝', title: 'GemiMark IDE', width: 700, html: (pid) => `<div style="display:flex; flex-grow:1; gap:10px;"><textarea id="md-in-${pid}" oninput="GemiOS.Registry['GemiMark.app'].parse(${pid})" style="flex:1; background:#1e1e1e; color:#d4d4d4; font-family:monospace; padding:15px; border:none; border-radius:6px; resize:none; outline:none; font-size:14px;" spellcheck="false"># GemiMark\n\nLive **Markdown** rendering.\n\n* Fast\n* Native\n* Cool</textarea><div id="md-out-${pid}" style="flex:1; background:rgba(255,255,255,0.9); color:black; padding:15px; border-radius:6px; overflow-y:auto; font-family:sans-serif;"><h1>GemiMark</h1><p>Live <b>Markdown</b> rendering.</p><ul><li>Fast</li><li>Native</li><li>Cool</li></ul></div></div>`, parse: (pid) => { let txt = document.getElementById(`md-in-${pid}`).value; let html = txt.replace(/^### (.*$)/gim, '<h3>$1</h3>').replace(/^## (.*$)/gim, '<h2>$1</h2>').replace(/^# (.*$)/gim, '<h1>$1</h1>').replace(/^\> (.*$)/gim, '<blockquote>$1</blockquote>').replace(/\*\*(.*)\*\*/gim, '<b>$1</b>').replace(/\*(.*)\*/gim, '<i>$1</i>').replace(/^\* (.*$)/gim, '<ul><li>$1</li></ul>').replace(/<\/ul>\n<ul>/gim, '').replace(/\n$/gim, '<br>'); document.getElementById(`md-out-${pid}`).innerHTML = html; } },
    'GemiLink.app': { desc: 'Peer-to-Peer file sharing.', icon: '🌍', title: 'GemiLink P2P', width: 450, html: (pid) => `<div class="sys-card" style="text-align:center;"><div style="font-size:40px;">🌍</div><div style="font-size:24px; font-weight:bold; color:var(--accent); letter-spacing:5px;" id="link-code-${pid}">-----</div><div style="display:flex; gap:10px; margin-top:10px;"><button class="btn-primary" onclick="document.getElementById('link-code-${pid}').innerText=Math.floor(10000+Math.random()*90000);">Host</button><button class="btn-sec" onclick="GemiOS.notify('GemiLink', 'Connected.');">Join</button></div></div>` },
    'GemiScript.app': { desc: 'OS automation macro IDE.', icon: '📜', title: 'GemiScript', width: 600, html: (pid) => `<div class="sys-card" style="margin-bottom:10px; font-size:12px;">Write custom JS. Use <code>GemiOS.notify()</code>.</div><textarea id="script-in-${pid}" style="flex-grow:1; background:#1e1e1e; color:#38ef7d; font-family:monospace; padding:10px; border:1px solid var(--accent); border-radius:6px; resize:none; outline:none; font-size:14px;" spellcheck="false">// GemiScript\nGemiOS.notify('Macro Executed', 'Automation successful!', true);\nGemiOS.PM.launch('app_calc');\n</textarea><div style="display:flex; gap:10px; margin-top:10px;"><button onclick="try{ eval(document.getElementById('script-in-${pid}').value); }catch(e){ GemiOS.notify('Error', e.message, false); }" class="btn-primary" style="flex:1;">▶️ Run</button><button onclick="GemiOS.VFS.write('C:/Users/'+GemiOS.user+'/Desktop', 'macro.gbs', document.getElementById('script-in-${pid}').value); GemiOS.renderDesktopIcons(); GemiOS.notify('GemiScript', 'Saved as .gbs');" class="btn-sec" style="flex:1; margin:0;">💾 Save</button></div>` },
    'GemiZip.app': { desc: 'Compress folders to .gzip.', icon: '🗜️', title: 'GemiZip', width: 400, html: (pid) => `<div class="sys-card" style="text-align:center; padding:30px; flex-grow:1;"><div style="font-size:50px;">🗜️</div><h3>Compression</h3><input type="text" id="zip-path-${pid}" value="C:/Users/${GemiOS.user}/Pictures" style="width:100%; padding:10px; border-radius:6px; border:none; outline:none; background:rgba(255,255,255,0.9); color:black;"><button onclick="GemiOS.compressFolder(document.getElementById('zip-path-${pid}').value)" class="btn-primary" style="margin-top:15px;">Compress</button></div>` },
    'GemiCalc Lab.app': { desc: 'Live Graphing Engine.', icon: '📈', title: 'GemiCalc Lab', width: 700, html: (pid) => `<div style="display:flex; gap:10px; flex-grow:1; height:380px;"><div style="flex:2; background:#000; border-radius:8px; border:1px solid var(--accent); position:relative; overflow:hidden;"><canvas id="calc-cvs-${pid}" style="width:100%; height:100%; display:block;"></canvas></div><div style="flex:1; background:rgba(0,0,0,0.4); padding:15px; border-radius:8px;"><select id="calc-fn-${pid}" style="width:100%; padding:5px;"><option value="x*x">f(x) = x²</option><option value="Math.sin(x)*5">f(x) = 5sin(x)</option></select><input type="range" id="calc-x-${pid}" min="-10" max="10" step="0.1" value="2" style="width:100%; margin-top:10px;"><div id="calc-stat-${pid}" style="font-family:monospace; margin-top:10px; color:#38ef7d;"></div></div></div>`, onLaunch: (pid) => { setTimeout(() => { let cvs = document.getElementById(`calc-cvs-${pid}`); let ctx = cvs.getContext('2d'); let fn = document.getElementById(`calc-fn-${pid}`); let xS = document.getElementById(`calc-x-${pid}`); let stat = document.getElementById(`calc-stat-${pid}`); GemiOS.calcItvs = GemiOS.calcItvs || {}; GemiOS.calcItvs[pid] = setInterval(() => { if(!document.getElementById(`calc-cvs-${pid}`)) { clearInterval(GemiOS.calcItvs[pid]); return; } cvs.width = cvs.offsetWidth; cvs.height = cvs.offsetHeight; ctx.fillStyle = "#0a0a0a"; ctx.fillRect(0,0,cvs.width,cvs.height); let cx = cvs.width/2, cy = cvs.height/2, sc = 20; ctx.strokeStyle="#333"; ctx.beginPath(); ctx.moveTo(0, cy); ctx.lineTo(cvs.width, cy); ctx.moveTo(cx, 0); ctx.lineTo(cx, cvs.height); ctx.stroke(); let f = (x)=>eval(fn.value); ctx.strokeStyle="var(--accent)"; ctx.beginPath(); for(let p=0; p<=cvs.width; p++) { let x=(p-cx)/sc; let y=f(x); if(p===0) ctx.moveTo(p, cy-y*sc); else ctx.lineTo(p, cy-y*sc); } ctx.stroke(); let cxV = parseFloat(xS.value); let cyV = f(cxV); stat.innerHTML = `x: ${cxV}<br>y: ${cyV.toFixed(2)}`; }, 50); }, 100); }, onKill: (pid) => { if(GemiOS.calcItvs && GemiOS.calcItvs[pid]) clearInterval(GemiOS.calcItvs[pid]); } },
    'GemiMail.app': { desc: 'Offline Email Client.', icon: '✉️', title: 'GemiMail', width: 550, html: (pid) => `<div style="display:flex; flex-grow:1; background:#fff; color:black; border-radius:6px; overflow:hidden;"><div style="width:200px; border-right:1px solid #ddd; background:#f5f5f5; display:flex; flex-direction:column;"><div style="padding:15px; font-weight:bold; border-bottom:1px solid #ddd;">Inbox</div><div id="mail-list-${pid}" style="flex-grow:1; overflow-y:auto;"></div></div><div id="mail-body-${pid}" style="flex-grow:1; padding:20px; font-family:sans-serif;"><h2 style="color:#aaa; text-align:center; margin-top:50px;">Select an email</h2></div></div>`, onLaunch: (pid) => { GemiOS.launchMail(pid); } },
    'GemiTubes.app': { desc: 'Native YouTube Video Player.', icon: '▶️', title: 'GemiTubes', width: 600, html: (pid) => `<div style="display:flex;gap:5px;margin-bottom:10px;"><input type="text" id="yt-id-${pid}" placeholder="Enter YouTube ID (e.g. dQw4w9WgXcQ)" style="flex-grow:1;padding:8px;border-radius:4px;border:none;outline:none;"><button onclick="let id = document.getElementById('yt-id-${pid}').value; if(id) document.getElementById('yt-frame-${pid}').src='https://www.youtube.com/embed/'+id;" class="btn-primary" style="width:auto;margin:0;">Play Native</button></div><iframe id="yt-frame-${pid}" style="width:100%;flex-grow:1;border:none;border-radius:8px;background:black;" allowfullscreen></iframe>` },
    'GemiVoice.app': { desc: 'Multi-voice TTS synthesizer.', icon: '🗣️', title: 'GemiVoice TTS', width: 450, html: (pid) => `<textarea id="voice-text-${pid}" style="flex-grow:1; width:100%; box-sizing:border-box; border:none; border-radius:6px; padding:15px; font-family:sans-serif; outline:none; background:rgba(255,255,255,0.9); color:black; margin-bottom:10px;">GemiOS 36.3: The Removal Update is installed.</textarea><button onclick="let u = new SpeechSynthesisUtterance(document.getElementById('voice-text-${pid}').value); speechSynthesis.speak(u);" class="btn-primary">🗣️ Speak</button>` },
    'GemiCam.app': { desc: 'Webcam with Motion Detection.', icon: '📸', title: 'GemiCam', width: 500, html: (pid) => `<div style="flex-grow:1; background:#000; border-radius:6px; overflow:hidden; position:relative; display:flex; justify-content:center; align-items:center;"><video id="vid-${pid}" autoplay playsinline style="width:100%; height:100%; object-fit:cover;"></video><button onclick="GemiOS.takePhoto(${pid})" style="position:absolute; bottom:25px; left:50%; transform:translateX(-50%); padding:12px 25px; border-radius:25px; border:2px solid white; background:#ff4d4d; color:white; font-weight:bold; cursor:pointer;">📸 Capture</button></div>`, onLaunch: (pid) => { navigator.mediaDevices.getUserMedia({video:true}).then(s => { let v = document.getElementById(`vid-${pid}`); if(v) { v.srcObject = s; GemiOS.camStreams = GemiOS.camStreams || {}; GemiOS.camStreams[pid] = s; } }).catch(e => { document.getElementById(`content_${pid}`).innerHTML = `<div class="sys-card" style="color:#ff4d4d;">Camera access denied.</div>`; }); }, onKill: (pid) => { if(GemiOS.camStreams && GemiOS.camStreams[pid]) GemiOS.camStreams[pid].getTracks().forEach(t=>t.stop()); } },
    'Gallery.app': { desc: 'Photo and image viewer.', icon: '🖼️', title: 'Gallery Viewer', width: 550, html: (pid, fileData) => { if(fileData) return `<div style="text-align:center; flex-grow:1; display:flex; align-items:center; justify-content:center;"><img src="${fileData}" style="max-width:100%; max-height:100%; border-radius:6px; box-shadow:0 5px 15px rgba(0,0,0,0.5);"></div>`; let pics = GemiOS.VFS.getDir('C:/Users/' + GemiOS.user + '/Pictures') || {}; let h = ''; for(let p in pics) { h += `<img src="${pics[p]}" style="width:100%; border-radius:6px; margin-bottom:15px; border:1px solid rgba(255,255,255,0.2);">`; } if(h === '') h = '<div style="text-align:center; padding:40px; opacity:0.5; font-size:18px; flex-grow:1;">No photos found. Drag & Drop to import!</div>'; return `<div style="flex-grow:1; overflow-y:auto; padding-right:5px;">${h}</div>`; } },
    'GemiCode.app': { desc: 'Live HTML/CSS Sandbox.', icon: '&lt;/&gt;', title: 'GemiCode', width: 800, html: (pid) => { let def = "<html>\n<body style='color:white;'>\n  <h2>Code!</h2>\n</body>\n</html>"; return `<div style="display:flex; flex-grow:1; gap:10px;"><textarea id="ide-in-${pid}" oninput="document.getElementById('ide-out-${pid}').srcdoc=this.value" style="flex:1; background:#1e1e1e; color:#d4d4d4; font-family:monospace; padding:10px; border:none; border-radius:6px; resize:none; outline:none;" spellcheck="false">${def}</textarea><iframe id="ide-out-${pid}" style="flex:1; background:rgba(0,0,0,0.5); border:1px solid rgba(255,255,255,0.2); border-radius:6px;" srcdoc="${def}"></iframe></div>`; } },
    'Web Browser.app': { desc: 'Wikipedia web surfer.', icon: '🌐', title: 'Web Browser', width: 750, html: (pid) => `<div style="display:flex; gap:8px; margin-bottom:10px;"><input type="text" id="b-url-${pid}" value="https://wikipedia.org" style="flex-grow:1; padding:8px 12px; border-radius:20px; border:none; outline:none; background:rgba(255,255,255,0.9); color:black;"><button onclick="document.getElementById('b-frame-${pid}').src=document.getElementById('b-url-${pid}').value" class="btn-primary" style="width:auto; padding:8px 16px;">Go</button></div><iframe id="b-frame-${pid}" src="https://wikipedia.org" style="width:100%; flex-grow:1; border:none; border-radius:8px; background:white;"></iframe>` },
    'Calculator.app': { desc: 'Standard arithmetic calculator.', icon: '🧮', title: 'Calculator', width: 260, html: (pid) => `<div style="background:rgba(255,255,255,0.9); color:black; padding:15px; font-size:28px; text-align:right; margin-bottom:10px; border-radius:6px; font-family:monospace;" id="cd-${pid}">0</div><div style="display:grid; grid-template-columns:repeat(4,1fr); gap:6px; flex-grow:1;">${['7','8','9','/','4','5','6','*','1','2','3','-','C','0','=','+'].map(b=>`<button style="padding:15px; background:rgba(255,255,255,0.2); border:1px solid rgba(255,255,255,0.1); cursor:pointer; font-weight:bold; border-radius:6px; color:inherit; font-size:16px;" onclick="let d=document.getElementById('cd-${pid}'); if('${b}'==='C') d.innerText='0'; else if('${b}'==='=') { try { d.innerText=eval(d.innerText); } catch(e){ d.innerText='Err'; } } else { if(d.innerText==='0') d.innerText='${b}'; else d.innerText+='${b}'; }">${b}</button>`).join('')}</div>` },
    'GemiPlayer.app': { desc: 'Universal Media Player.', icon: '🎵', title: 'GemiPlayer', width: 450, html: (pid, fd) => { if(!fd) return `<div class="sys-card" style="text-align:center; flex-grow:1;"><h2>🎵 GemiPlayer</h2><p>Drag .mp3 or .mp4 here.</p></div>`; return `<div style="background:#000; flex-grow:1; display:flex; justify-content:center; align-items:center; border-radius:6px; overflow:hidden;"><video controls autoplay style="width:100%; max-height:100%;"><source src="${fd}"></video></div>`; } },
    'GemiSheets.app': { desc: 'Spreadsheet office tool.', icon: '📊', title: 'GemiSheets', width: 600, html: (pid) => { let h = '<div style="flex-grow:1; background:#fff; color:#000; overflow:auto; border-radius:6px; padding:5px;"><table style="width:100%; border-collapse:collapse; font-size:12px;"><tr><th></th>'; for(let c=0; c<5; c++) h += `<th style="border:1px solid #ccc; background:#eee;">${String.fromCharCode(65+c)}</th>`; h += '</tr>'; for(let r=1; r<=12; r++) { h += `<tr><td style="border:1px solid #ccc; background:#eee; text-align:center; font-weight:bold;">${r}</td>`; for(let c=0; c<5; c++) { h += `<td style="border:1px solid #ccc; padding:0;"><input type="text" style="width:100%; border:none; outline:none; padding:4px;" onblur="GemiOS.evalSheet(this)"></td>`; } h += '</tr>'; } return h + '</table></div>'; } },
    'Paint.app': { desc: 'Digital drawing canvas.', icon: '🎨', title: 'GemiPaint', width: 600, html: (pid) => `<div style="margin-bottom:10px; display:flex; gap:10px; align-items:center;"><button onclick="const c=document.getElementById('cvs-${pid}'); c.getContext('2d').clearRect(0,0,c.width,c.height);" class="btn-sec" style="width:auto; margin:0; padding:6px 12px;">Clear</button> <input type="color" id="p-col-${pid}" value="#000000" style="cursor:pointer;"></div><canvas id="cvs-${pid}" style="background:white; border-radius:6px; width:100%; flex-grow:1; cursor:crosshair; box-shadow:inset 0 0 10px rgba(0,0,0,0.1);"></canvas>`, onLaunch: (pid) => { setTimeout(() => { const can = document.getElementById(`cvs-${pid}`); if(!can) return; can.width = can.offsetWidth; can.height = can.offsetHeight; const ctx = can.getContext('2d'); let d = false; can.onmousedown = (e) => { d = true; ctx.beginPath(); ctx.moveTo(e.offsetX, e.offsetY); }; can.onmouseup = () => d = false; can.onmousemove = (e) => { if(d) { ctx.lineTo(e.offsetX, e.offsetY); ctx.strokeStyle = document.getElementById(`p-col-${pid}`).value; ctx.lineWidth = 4; ctx.lineCap = 'round'; ctx.stroke(); } }; window.addEventListener('resize', () => { if(can.width !== can.offsetWidth) { let temp = ctx.getImageData(0,0,can.width,can.height); can.width = can.offsetWidth; can.height = can.offsetHeight; ctx.putImageData(temp,0,0); } }); }, 100); } },
};
